### ISSUE TITLE
如何使用您设计的字体

### ISSUE THREAD

**Issue by OumCc** [wentin/CSS-Mono#1]
您好，在 **中国第三届CSS开发者大会** 上看到您设计的字体之后，特别喜欢，很想自己的编辑器也用上这种字体，不过不知道如何使用( ˇˍˇ )

PS：
- [css-mono](http://css-mono.wentin.co)——这里面我注册了好像也下载不了
- github上的 `Code` `Design` `Export`这三个文件夹应该`Export`是输出的吧？不过为什么里面有那么多个字体文件？
- 我使用的编辑器是sublime，IDE是webstorm，系统是Windows，应该都可以用上吧（好像只要系统可以安装了字体，其它软件都可以用上？）

**Comment by wentin** [comment]
您好，目前我还在修改字体，还没有正式发布，粗细上我还在修改。如果你想使用，可以在export里下载数字最大的（即最新的），安装在电脑上。字体名称为"css mono" 在sublime里可以设置。
"font_face": "CSS Mono",

**Comment by OumCc** [comment]
谢谢，已经测试过，是可以的(*^__^*) 嘻嘻……

提点小建议：
- 为什么字体命名用空格隔开？
- `"font_face": "CSS Mono YaHei Consolas Hybrid",` ——如果想要这样多种字体共存的形式，就有问题（主要是想一个中文字体，一个英文字体）

**Comment by wentin** [comment]
好，我调查一下，最好是在code里达到用css-mono来指代

**Comment by Leafyyuki** [comment]
请问在vscode里面要怎么设置呢？
在sublime里面我用上面的方式设置成功了，
在vscode里面这样设置 "editor.fontFamily": "CSS Mono“ 没有生效。

**Comment by wentin** [comment]
@Leafyyuki 
I updated the `README.md` you can refer to this
https://github.com/wentin/CSS-Mono/blob/master/README.md

I downloaded the VS Code and followed the instructions, it worked for me. 
Uninstall the font and download the files again using the links provided, and try again. Hope it works!
:)

**Comment by Leafyyuki** [comment]
I installed the font again using the links provided, and it worked!
Thanks for your replying!
