### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by jer0701** [wentin/CSS-Mono#2]
![image](https://user-images.githubusercontent.com/18334131/32429663-92585d32-c306-11e7-9220-4185e251d1e7.png)
Hello wentin，Download the latest version and installed, set  "font_face": "CSS Mono" or  "font_face": "CSS Mono Italic" in sublime. But it doesn't work. Why? What step need to do？

**Comment by wentin** [comment]
That is all the steps required. What OS(windows or Mac OS) are you using? And were you able to change to other fonts? Did you restart your sublime?

**Comment by CoatiFly** [comment]
@jer0701 you need to be in the OS install  new fonts，And then you can set it up.

**Comment by jer0701** [comment]
It's ok！ I forgot to rewrite in Settings - User，just write in the Settings - Default is invalid.
This font is very special, I like it！ Thanks
