### ISSUE TITLE
Is there any articles/vidios to introduce "CSS Mono"?

### ISSUE THREAD

**Issue by jeasonstudio** [wentin/CSS-Mono#3]
or just tell us what does "CSS Mono is a typeface designed and optimized specifically to be used to write and read CSS code" mean, how to Embody?
Thanks to your job.

**Comment by wentin** [comment]
When the typeface is officially done and launched, I will make a video and article about the design intent and process, thanks for the request! 
How to embed the font can be fond in the `README.md` file.
